homepage_settings:
  countdown:
    show: true
    timezone: Europe/Berlin
    deadline: 2026-09-02 08:59
  modal:
    show: false
    delay: 4000
  testimonials:
    show: true
    title: "What others said about MQ Summit"
  gallery:
    show: true
    title: "How was it in 2025?"
  tickets: true
