homepage_settings:
  countdown:
    show: true
    timezone: Europe/Berlin
    deadline: 2025-10-28 23:59
  modal:
    show: false
    delay: 4000
  testimonials:
    show: true
    title: "What others said about RabbitMQ Summit"
  gallery:
    show: true
    title: "How was RabbitMQ Summit?"
  tickets: true
