homepage_settings:
  countdown:
    show: false
    timezone: Europe/Berlin
    deadline: 2024-10-14 08:30
  modal:
    show: false
    delay: 4000
  testimonials:
    show: true
    title: "What others said about RabbitMQ Summit"
  gallery:
    show: true
    title: "How was RabbitMQ Summit?"
  tickets: false
