---
trainers:
- _participants/robert-virding.md
- _participants/lukasz-pauszek.md
- _participants/hayleigh-thompson.md
- _participants/giacomo-cavalieri.md
- _participants/sasa-juric.md
- _participants/brujo-benavides.md
- _participants/pablo-costas.md
- _participants/dmytro-lytovchenko.md
