name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.5'
        bundler-cache: true
    - name: Build the site with Jekyll
      run: bundle exec jekyll build --future
      env:
        JEKYLL_ENV: production
        LANG: C.UTF-8
        LC_ALL: C.UTF-8
